<?php

namespace App\Core\Exceptions;

enum ErrorCode: string
{
    case VALIDATION_ERROR = 'VALIDATION_ERROR';
    case UNAUTHORIZED = 'UNAUTHORIZED';
    case FORBIDDEN = 'FORBIDDEN';
    case NOT_FOUND = 'NOT_FOUND';
    case METHOD_NOT_ALLOWED = 'METHOD_NOT_ALLOWED';
    case INTERNAL_ERROR = 'INTERNAL_ERROR';

    case EMAIL_ALREADY_EXISTS = 'EMAIL_ALREADY_EXISTS';
    case INVALID_CREDENTIALS = 'INVALID_CREDENTIALS';

    // Microservice / integration
    case MICROSERVICE_UNAVAILABLE = 'MICROSERVICE_UNAVAILABLE';
    case MICROSERVICE_ERROR = 'MICROSERVICE_ERROR';
    case MICROSERVICE_BAD_RESPONSE = 'MICROSERVICE_BAD_RESPONSE';

    // Anti-spam
    case SPAM_BLOCKED = 'SPAM_BLOCKED';
}
